defaults:
  - override hydra/launcher: submitit_slurm

hydra:
  job:
    name: "train_model"
  run:
    dir: ./logs/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./logs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: cfg:${hydra.job.override_dirname}/
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 1420
    cpus_per_task: 10
    mem_gb: 64
    nodes: 1
    name: ${hydra.job.name}
    partition: "gpu"
    gpus_per_task: 1
    array_parallelism: 4
    setup:
      - conda activate hard-feat
