defaults:
  - hydra_base
  - data/base
  - logging/wandb
  - _self_

run:
  name: "train-perceptron-corrupted-data"

model:
  hidden_dims: [1000, 10]
  activations: ["relu", "identity"]
  lr: 1e-3
  weight_decay: 0

data:
  name: mnist
  num_channels: 1
  num_classes: 10
  num_workers: 0
  batch_size: 128

corruption:
  key: "rotation"
  args:
  # random
  #  image_shape: [1, 28, 28]
  #  pixel_ratio: 0.1
  #  seed: 44

  # flatten
  # placeholder: 1

  # rotation
    degrees: 180

trainer:
  max_epochs: 100
  accelerator: "auto"
  devices: "auto"
